/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Constants, ConstantsInterface } from "../Constants";

const _abi = [
  {
    inputs: [],
    name: "MANAGER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ORACLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROPOSAL_TYPEHASH",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROPOSER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x7faf290d8680820aad922855f39b306097b20e28774d6c1ad35a20325630c3a02c6080527f352d05fe3946dbe49277552ba941e744d5a96d9c60bc1ba0ea5f1d3ae000f7c860a0527fc4338366b9cfc07901c46677a3a32746bd05d5c114e4d0d293c468cff87acde060c0527f50726f706f73616c2862797465733332206665656449642c75696e7433322074610120527f696d657374616d702c696e743235362076616c75652c62797465733332206461610140526274612960e81b610160526043610100526101636040527f66741b1f89239b29850421f111693bb50fc04af1e25692c4f6b30ce08f5cf4a060e0523480156100fc57600080fd5b5060805160a05160c05160e05161012b610132600039600060ad0152600060d301526000608701526000604f015261012b6000f3fe6080604052348015600f57600080fd5b506004361060465760003560e01c80631b2df85014604b57806338013f02146083578063853b94a01460a9578063bffa7f0f1460cf575b600080fd5b60717f000000000000000000000000000000000000000000000000000000000000000081565b60405190815260200160405180910390f35b60717f000000000000000000000000000000000000000000000000000000000000000081565b60717f000000000000000000000000000000000000000000000000000000000000000081565b60717f00000000000000000000000000000000000000000000000000000000000000008156fea26469706673582212203f90ffdad8fbdf6afd7471f09ad43ce7d04f41833c7bf2e6490a2d130947f37264736f6c63430008090033";

export class Constants__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Constants> {
    return super.deploy(overrides || {}) as Promise<Constants>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Constants {
    return super.attach(address) as Constants;
  }
  connect(signer: Signer): Constants__factory {
    return super.connect(signer) as Constants__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ConstantsInterface {
    return new utils.Interface(_abi) as ConstantsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Constants {
    return new Contract(address, _abi, signerOrProvider) as Constants;
  }
}
