/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SkinnyOptimisticOracleInterfaceInterface
  extends ethers.utils.Interface {
  functions: {
    "disputePrice(address,bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "disputePriceFor(bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256),address,address)": FunctionFragment;
    "getState(address,bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "hasPrice(address,bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "proposePrice(address,bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256),int256)": FunctionFragment;
    "proposePriceFor(address,bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256),address,int256)": FunctionFragment;
    "requestAndProposePriceFor(bytes32,uint32,bytes,address,uint256,uint256,uint256,address,int256)": FunctionFragment;
    "requestPrice(bytes32,uint32,bytes,address,uint256,uint256,uint256)": FunctionFragment;
    "settle(address,bytes32,uint32,bytes,(address,address,address,bool,int256,int256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "stampAncillaryData(bytes,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "disputePrice",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disputePriceFor",
    values: [
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getState",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPrice",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proposePrice",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proposePriceFor",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAndProposePriceFor",
    values: [
      BytesLike,
      BigNumberish,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestPrice",
    values: [
      BytesLike,
      BigNumberish,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [
      string,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "stampAncillaryData",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "disputePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputePriceFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposePriceFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAndProposePriceFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stampAncillaryData",
    data: BytesLike
  ): Result;

  events: {
    "DisputePrice(address,bytes32,uint32,bytes,tuple)": EventFragment;
    "ProposePrice(address,bytes32,uint32,bytes,tuple)": EventFragment;
    "RequestPrice(address,bytes32,uint32,bytes,tuple)": EventFragment;
    "Settle(address,bytes32,uint32,bytes,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DisputePrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposePrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Settle"): EventFragment;
}

export type DisputePriceEvent = TypedEvent<
  [
    string,
    string,
    number,
    string,
    [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    }
  ] & {
    requester: string;
    identifier: string;
    timestamp: number;
    ancillaryData: string;
    request: [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    };
  }
>;

export type ProposePriceEvent = TypedEvent<
  [
    string,
    string,
    number,
    string,
    [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    }
  ] & {
    requester: string;
    identifier: string;
    timestamp: number;
    ancillaryData: string;
    request: [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    };
  }
>;

export type RequestPriceEvent = TypedEvent<
  [
    string,
    string,
    number,
    string,
    [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    }
  ] & {
    requester: string;
    identifier: string;
    timestamp: number;
    ancillaryData: string;
    request: [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    };
  }
>;

export type SettleEvent = TypedEvent<
  [
    string,
    string,
    number,
    string,
    [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    }
  ] & {
    requester: string;
    identifier: string;
    timestamp: number;
    ancillaryData: string;
    request: [
      string,
      string,
      string,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumber;
      resolvedPrice: BigNumber;
      expirationTime: BigNumber;
      reward: BigNumber;
      finalFee: BigNumber;
      bond: BigNumber;
      customLiveness: BigNumber;
    };
  }
>;

export class SkinnyOptimisticOracleInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SkinnyOptimisticOracleInterfaceInterface;

  functions: {
    disputePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disputePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      disputer: string,
      requester: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getState(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasPrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposePriceFor(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestAndProposePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestPrice(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settle(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stampAncillaryData(
      ancillaryData: BytesLike,
      requester: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  disputePrice(
    requester: string,
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disputePriceFor(
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    disputer: string,
    requester: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getState(
    requester: string,
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasPrice(
    requester: string,
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposePrice(
    requester: string,
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    proposedPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposePriceFor(
    requester: string,
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    proposer: string,
    proposedPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestAndProposePriceFor(
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    currency: string,
    reward: BigNumberish,
    bond: BigNumberish,
    customLiveness: BigNumberish,
    proposer: string,
    proposedPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestPrice(
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    currency: string,
    reward: BigNumberish,
    bond: BigNumberish,
    customLiveness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settle(
    requester: string,
    identifier: BytesLike,
    timestamp: BigNumberish,
    ancillaryData: BytesLike,
    request: {
      proposer: string;
      disputer: string;
      currency: string;
      settled: boolean;
      proposedPrice: BigNumberish;
      resolvedPrice: BigNumberish;
      expirationTime: BigNumberish;
      reward: BigNumberish;
      finalFee: BigNumberish;
      bond: BigNumberish;
      customLiveness: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stampAncillaryData(
    ancillaryData: BytesLike,
    requester: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    disputePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    disputePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      disputer: string,
      requester: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getState(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<number>;

    hasPrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<boolean>;

    proposePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposedPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposePriceFor(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestAndProposePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestPrice(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    settle(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { payout: BigNumber; resolvedPrice: BigNumber }
    >;

    stampAncillaryData(
      ancillaryData: BytesLike,
      requester: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DisputePrice(address,bytes32,uint32,bytes,tuple)"(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    DisputePrice(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    "ProposePrice(address,bytes32,uint32,bytes,tuple)"(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    ProposePrice(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    "RequestPrice(address,bytes32,uint32,bytes,tuple)"(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    RequestPrice(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    "Settle(address,bytes32,uint32,bytes,tuple)"(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;

    Settle(
      requester?: string | null,
      identifier?: BytesLike | null,
      timestamp?: null,
      ancillaryData?: null,
      request?: null
    ): TypedEventFilter<
      [
        string,
        string,
        number,
        string,
        [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        }
      ],
      {
        requester: string;
        identifier: string;
        timestamp: number;
        ancillaryData: string;
        request: [
          string,
          string,
          string,
          boolean,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          proposer: string;
          disputer: string;
          currency: string;
          settled: boolean;
          proposedPrice: BigNumber;
          resolvedPrice: BigNumber;
          expirationTime: BigNumber;
          reward: BigNumber;
          finalFee: BigNumber;
          bond: BigNumber;
          customLiveness: BigNumber;
        };
      }
    >;
  };

  estimateGas: {
    disputePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disputePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      disputer: string,
      requester: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getState(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasPrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposePriceFor(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestAndProposePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestPrice(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settle(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stampAncillaryData(
      ancillaryData: BytesLike,
      requester: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disputePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disputePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      disputer: string,
      requester: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getState(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasPrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposePrice(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposePriceFor(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestAndProposePriceFor(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      proposer: string,
      proposedPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestPrice(
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      currency: string,
      reward: BigNumberish,
      bond: BigNumberish,
      customLiveness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settle(
      requester: string,
      identifier: BytesLike,
      timestamp: BigNumberish,
      ancillaryData: BytesLike,
      request: {
        proposer: string;
        disputer: string;
        currency: string;
        settled: boolean;
        proposedPrice: BigNumberish;
        resolvedPrice: BigNumberish;
        expirationTime: BigNumberish;
        reward: BigNumberish;
        finalFee: BigNumberish;
        bond: BigNumberish;
        customLiveness: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stampAncillaryData(
      ancillaryData: BytesLike,
      requester: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
